name: verify

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  packer-fmt:
    uses: mateusz-uminski/github-actions/.github/workflows/packer-lint-fmt.yaml@main
    with:
      packer_version: 1.11.2

  yamllint:
    uses: mateusz-uminski/github-actions/.github/workflows/yamllint.yaml@main
    with:
      python_version: 3.11
      yamllint_version: 1.33.0

  python-lint:
    uses: mateusz-uminski/github-actions/.github/workflows/python-lint.yaml@main
    with:
      python_version: 3.11
      flake8_version: 6.1.0

  terraform-fmt:
    uses: mateusz-uminski/github-actions/.github/workflows/terraform-lint-fmt.yaml@main
    with:
      terraform_version: 1.9.6
